# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "modernIE/w7-ie11"

  config.vm.hostname = "duplin-jhonston-vsamban-mct"

  config.vm.boot_timeout = 600

  config.vm.guest = :windows

  config.vm.communicator = "winrm"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true

     vb.memory = "2048"
	   vb.customize ["modifyvm", :id, "--vram", "64"]
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
     vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
	   vb.name = "duplin-jhonston-vsamban-mct"
   end

  config.vm.network :forwarded_port, guest: 3389, host: 3377, id: "rdp", auto_correct: false
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  config.windows.set_work_network = true
  config.winrm.max_tries = 10

  config.vm.provision :shell, path: "installChoco.bat"
  config.vm.provision :shell, path: "installsoft.bat"
  config.vm.provision :shell, path: "installTools.bat"

end
