# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	unless Vagrant.has_plugin?("vagrant-reload")
    abort 'Plugin needed: vagrant-reload. Run the following command to install: vagrant plugin install vagrant-reload'
  end
  config.vm.box = "modernIE/w7-ie11"

  config.vm.hostname = "duplin-jhonston-vsamban-mct"

  config.vm.guest = :windows
  
  def os
  @os ||= (
    host_os = RbConfig::CONFIG['host_os']
    case host_os
    when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
      :windows
    when /darwin|mac os/
      :macosx
    when /linux/
      :linux
    when /solaris|bsd/
      :unix
    else
      raise Error::WebDriverError, "unknown os: #{host_os.inspect}"
    end
)
end

if os() == :windows
  audio = 'dsound'
else
  audio = 'oss'
end

  config.vm.communicator = "winrm"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true

     vb.memory = "2048"
	   vb.customize ["modifyvm", :id, "--vram", "64"]
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
     vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
	  vb.customize ["modifyvm", :id, "--ioapic", "on"]
	 vb.customize ["modifyvm", :id, "--audio", audio, "--audiocontroller", "ac97"]
	   vb.name = "duplin-jhonston-vsamban-mct"
   end

  config.vm.network :forwarded_port, guest: 3389, host: 3377, id: "rdp", auto_correct: false
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  config.windows.set_work_network = true
  config.winrm.max_tries = 10

  config.vm.provision :shell, path: "installChoco.bat"
  config.vm.provision :shell, path: "installsoft.bat"
  config.vm.provision :shell, path: "installTools.bat"
  config.vm.provision :reload

end
